### ISSUE TITLE
Set up the kanban board 

### ISSUE THREAD

**Issue by ridabensalem** [ridabensalem/ruby-capstone#23]
The link to the ruby capstone project : [ruby capstone project](https://github.com/ridabensalem/ruby-capstone/projects/1)
**Note: We are three members in this project** 
- Team member 1: @ridabensalem 
- Team member 2 : @yegonkimutai 
- Team member 3 : @adarachel

**Comment by binhussen** [comment]
Hi @ridabensalem, @yegonkimutai and @adarachel, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- Set uped Kanban board ✔️
- Fairway distributed tasks✔️
- Descriptive title with number of points Tasks ✔️

## Required Changes ♻️
- Kindly, you missed defining [group tasks](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task) in the Kanban board, please be sure to have a corresponding card in the Kanban board as its part of the requirement.👍
![Screenshot 2023-07-03 141207](https://github.com/ridabensalem/ruby-capstone/assets/52010789/fd0665ec-7dc6-46d5-bf46-9b64a72d72e3)
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ridabensalem** [comment]
Thank you, the group tasks have been added

**Comment by binhussen** [comment]
Hi @ridabensalem, @yegonkimutai and @adarachel 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Set uped Kanban board ✔️
- Fairway distributed tasks✔️
- Descriptive title with number of points Tasks ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
